/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.wbd101.hrvdemo;

public class AndroidHRVStressAPIJNI {
  public final static native int get_percentage_stress(double jarg1, int jarg2);
  static {
    System.loadLibrary("HRV-lib");
  }
}
