/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.wbd101.hrvdemo;

public class AndroidRespirationAPI {
  public static void init_respiration_analysis() {
    AndroidRespirationAPIJNI.init_respiration_analysis();
  }

  public static void analyze_respiration(float this_rri) {
    AndroidRespirationAPIJNI.analyze_respiration(this_rri);
  }

  public static respiration_result_t get_respiration_result() {
    return new respiration_result_t(AndroidRespirationAPIJNI.get_respiration_result(), true);
  }

}
