/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.wbd101.hrvdemo;

public class AndroidHRVAPI {
  public static hrv_result_t HRV_Get_Analysis_Result() {
    return new hrv_result_t(AndroidHRVAPIJNI.HRV_Get_Analysis_Result(), true);
  }

  public static void init_hrv_analysis() {
    AndroidHRVAPIJNI.init_hrv_analysis();
  }

  public static void hrv_analysis(int thistime, short hr, short rr) {
    AndroidHRVAPIJNI.hrv_analysis(thistime, hr, rr);
  }

}
