/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
    SWIG_JavaOutOfMemoryError = 1,
    SWIG_JavaIOException,
    SWIG_JavaRuntimeException,
    SWIG_JavaIndexOutOfBoundsException,
    SWIG_JavaArithmeticException,
    SWIG_JavaIllegalArgumentException,
    SWIG_JavaNullPointerException,
    SWIG_JavaDirectorPureVirtual,
    SWIG_JavaUnknownError,
    SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
    SWIG_JavaExceptionCodes code;
    const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
    jclass excep;
    static const SWIG_JavaExceptions_t java_exceptions[] = {
            { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
            { SWIG_JavaIOException, "java/io/IOException" },
            { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
            { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
            { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
            { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
            { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
            { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
            { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
            { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
            { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
    };
    const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

    while (except_ptr->code != code && except_ptr->code)
        except_ptr++;

    (*jenv)->ExceptionClear(jenv);
    excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
    if (excep)
        (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include <stdint.h>		// Use the C99 official header
#include <stdbool.h>


#include "respiration_functions.h"
#include "iOSHRVStressAPI.h"
#include "hrv_functions.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1total_1rr_1cnt_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jlong jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    uint32_t result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (uint32_t) ((arg1)->total_rr_cnt);
    jresult = (jlong)result;
    return jresult;
}


SWIGEXPORT jint JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1window_1rr_1cnt_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jint jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    uint16_t result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (uint16_t) ((arg1)->window_rr_cnt);
    jresult = (jint)result;
    return jresult;
}


SWIGEXPORT jint JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1valid_1rr_1cnt_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jint jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    uint16_t result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (uint16_t) ((arg1)->valid_rr_cnt);
    jresult = (jint)result;
    return jresult;
}


SWIGEXPORT jint JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1result_1timestamp_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jint jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    int result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (int) ((arg1)->result_timestamp);
    jresult = (jint)result;
    return jresult;
}


SWIGEXPORT jbyte JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1result_1conf_1level_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jbyte jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    int8_t result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (int8_t) ((arg1)->result_conf_level);
    jresult = (jbyte)result;
    return jresult;
}


SWIGEXPORT jshort JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1stress_1index_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jshort jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    int16_t result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (int16_t) ((arg1)->stress_index);
    jresult = (jshort)result;
    return jresult;
}


SWIGEXPORT jbyte JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1pNN50_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jbyte jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    int8_t result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (int8_t) ((arg1)->pNN50);
    jresult = (jbyte)result;
    return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1rMSSD_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jfloat jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    float result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (float) ((arg1)->rMSSD);
    jresult = (jfloat)result;
    return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1SDNN180_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jfloat jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    float result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (float) ((arg1)->SDNN180);
    jresult = (jfloat)result;
    return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1HRV_1Score_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jfloat jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    float result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (float) ((arg1)->HRV_Score);
    jresult = (jfloat)result;
    return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1dfa_1slope1_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jfloat jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    float result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (float) ((arg1)->dfa_slope1);
    jresult = (jfloat)result;
    return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1dfa_1slope2_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jfloat jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    float result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (float) ((arg1)->dfa_slope2);
    jresult = (jfloat)result;
    return jresult;
}


SWIGEXPORT jbyte JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1respiratory_1rate_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jbyte jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    int8_t result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (int8_t) ((arg1)->respiratory_rate);
    jresult = (jbyte)result;
    return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1vlf_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jfloat jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    float result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (float) ((arg1)->vlf);
    jresult = (jfloat)result;
    return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1lf_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jfloat jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    float result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (float) ((arg1)->lf);
    jresult = (jfloat)result;
    return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1hf_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jfloat jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    float result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (float) ((arg1)->hf);
    jresult = (jfloat)result;
    return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1lf_1nu_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jfloat jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    float result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (float) ((arg1)->lf_nu);
    jresult = (jfloat)result;
    return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1hf_1nu_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jfloat jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    float result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (float) ((arg1)->hf_nu);
    jresult = (jfloat)result;
    return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1lf_1to_1hf_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jfloat jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    float result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (float) ((arg1)->lf_to_hf);
    jresult = (jfloat)result;
    return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1result_1t_1total_1power_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jfloat jresult = 0 ;
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;
    float result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(hrv_result_t **)&jarg1;
    result = (float) ((arg1)->total_power);
    jresult = (jfloat)result;
    return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_new_1hrv_1result_1t(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    hrv_result_t *result = 0 ;

    (void)jenv;
    (void)jcls;
    result = (hrv_result_t *)calloc(1, sizeof(hrv_result_t));
    *(hrv_result_t **)&jresult = result;
    return jresult;
}


SWIGEXPORT void JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_delete_1hrv_1result_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    hrv_result_t *arg1 = (hrv_result_t *) 0 ;

    (void)jenv;
    (void)jcls;
    arg1 = *(hrv_result_t **)&jarg1;
    free((char *) arg1);
}


SWIGEXPORT jlong JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_HRV_1Get_1Analysis_1Result(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    hrv_result_t result;

    (void)jenv;
    (void)jcls;
    result = HRV_Get_Analysis_Result();
    {
        hrv_result_t * resultptr = (hrv_result_t *) malloc(sizeof(hrv_result_t));
        memmove(resultptr, &result, sizeof(hrv_result_t));
        *(hrv_result_t **)&jresult = resultptr;
    }
    return jresult;
}


SWIGEXPORT void JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_init_1hrv_1analysis(JNIEnv *jenv, jclass jcls) {
    (void)jenv;
    (void)jcls;
    init_hrv_analysis();
}


SWIGEXPORT void JNICALL Java_com_wbd101_hrvdemo_AndroidHRVAPIJNI_hrv_1analysis(JNIEnv *jenv, jclass jcls, jint jarg1, jshort jarg2, jshort jarg3) {
    int arg1 ;
    uint8_t arg2 ;
    int16_t arg3 ;

    (void)jenv;
    (void)jcls;
    arg1 = (int)jarg1;
    arg2 = (uint8_t)jarg2;
    arg3 = (int16_t)jarg3;
    hrv_analysis(arg1,arg2,arg3);
}
SWIGEXPORT jshort JNICALL Java_com_wbd101_hrvdemo_AndroidRespirationAPIJNI_respiration_1result_1t_1respiratory_1rate_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jshort jresult = 0 ;
    respiration_result_t *arg1 = (respiration_result_t *) 0 ;
    uint8_t result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(respiration_result_t **)&jarg1;
    result = (uint8_t) ((arg1)->respiratory_rate);
    jresult = (jshort)result;
    return jresult;
}


SWIGEXPORT jfloat JNICALL Java_com_wbd101_hrvdemo_AndroidRespirationAPIJNI_respiration_1result_1t_1respiration_1current_1depth_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jfloat jresult = 0 ;
    respiration_result_t *arg1 = (respiration_result_t *) 0 ;
    float result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(respiration_result_t **)&jarg1;
    result = (float) ((arg1)->respiration_current_depth);
    jresult = (jfloat)result;
    return jresult;
}


SWIGEXPORT jboolean JNICALL Java_com_wbd101_hrvdemo_AndroidRespirationAPIJNI_respiration_1result_1t_1is_1inspirating_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
    jboolean jresult = 0 ;
    respiration_result_t *arg1 = (respiration_result_t *) 0 ;
    bool result;

    (void)jenv;
    (void)jcls;
    (void)jarg1_;
    arg1 = *(respiration_result_t **)&jarg1;
    result = (bool) ((arg1)->is_inspirating);
    jresult = (jboolean)result;
    return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_wbd101_hrvdemo_AndroidRespirationAPIJNI_new_1respiration_1result_1t(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    respiration_result_t *result = 0 ;

    (void)jenv;
    (void)jcls;
    result = (respiration_result_t *)calloc(1, sizeof(respiration_result_t));
    *(respiration_result_t **)&jresult = result;
    return jresult;
}


SWIGEXPORT void JNICALL Java_com_wbd101_hrvdemo_AndroidRespirationAPIJNI_delete_1respiration_1result_1t(JNIEnv *jenv, jclass jcls, jlong jarg1) {
    respiration_result_t *arg1 = (respiration_result_t *) 0 ;

    (void)jenv;
    (void)jcls;
    arg1 = *(respiration_result_t **)&jarg1;
    free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_com_wbd101_hrvdemo_AndroidRespirationAPIJNI_init_1respiration_1analysis(JNIEnv *jenv, jclass jcls) {
    (void)jenv;
    (void)jcls;
    init_respiration_analysis();
}


SWIGEXPORT void JNICALL Java_com_wbd101_hrvdemo_AndroidRespirationAPIJNI_analyze_1respiration(JNIEnv *jenv, jclass jcls, jfloat jarg1) {
    float arg1 ;

    (void)jenv;
    (void)jcls;
    arg1 = (float)jarg1;
    analyze_respiration(arg1);
}


SWIGEXPORT jlong JNICALL Java_com_wbd101_hrvdemo_AndroidRespirationAPIJNI_get_1respiration_1result(JNIEnv *jenv, jclass jcls) {
    jlong jresult = 0 ;
    respiration_result_t result;

    (void)jenv;
    (void)jcls;
    result = get_respiration_result();
    {
        respiration_result_t * resultptr = (respiration_result_t *) malloc(sizeof(respiration_result_t));
        memmove(resultptr, &result, sizeof(respiration_result_t));
        *(respiration_result_t **)&jresult = resultptr;
    }
    return jresult;
}
SWIGEXPORT jint JNICALL Java_com_wbd101_hrvdemo_AndroidHRVStressAPIJNI_get_1percentage_1stress(JNIEnv *jenv, jclass jcls, jdouble jarg1, jint jarg2) {
    jint jresult = 0 ;
    double arg1 ;
    int arg2 ;
    int result;

    (void)jenv;
    (void)jcls;
    arg1 = (double)jarg1;
    arg2 = (int)jarg2;
    result = (int)get_percentage_stress(arg1,arg2);
    jresult = (jint)result;
    return jresult;
}



#ifdef __cplusplus
}
#endif